default['wordpress.test']['db_user'] = 'wordpressuser'
default['wordpress.test']['db_name'] = 'wordpressdb'
default['wordpress.test']['db_passwd'] = 'wordpresspasswd'
default['wordpress.test']['server_name'] = 'wordpress.local'
default['wordpress.test']['docroot'] = '/home/vagrant/public_html/'
